"use strict";
// This module is requier for rendering angular website...
var platform_browser_dynamic_1 = require("@angular/platform-browser-dynamic");
//this module need for rendering the website...This will allow us to bootstrap,or launch, the application...
var app_module_1 = require("./app.module");
//decoretor adds more behaviour to our class from outside of class.decorator code must be declare immediately before the class.
//decorator turns our plain old JavaScript class into a Component.It is one type of metadata...
platform_browser_dynamic_1.platformBrowserDynamic().bootstrapModule(app_module_1.AppModule); ///render application using platformBrowserDynamic module...
//# sourceMappingURL=main.js.map